### ISSUE TITLE
Question about the data

### ISSUE THREAD

**Issue by liwenssss** [bharat-b7/MultiGarmentNetwork#1]
Hi, if I want to train the model, where can get the dataset mentioned in the paper¿

**Comment by bharat-b7** [comment]
We are working on the dataset and will release it shortly.

**Comment by liwenssss** [comment]
And I noticed that &nbsp;the code &nbsp;seems not enough to &nbsp;run a &nbsp;test .No offense, I just interested in it and really want to see the resault.



发自我的iPhone


------------------ Original ------------------

**Comment by bharat-b7** [comment]
Could you provide details regarding the issue?

**Comment by Frank-Dz** [comment]
> We are working on the dataset and will release it shortly.

Hi~ When will you release the train code? Thanks~
