### ISSUE TITLE
How to use your own clothing data

### ISSUE THREAD

**Issue by yangbiaobiao500** [bharat-b7/MultiGarmentNetwork#10]
Although digital wardrobes show great results, what if I want to use my own data? How to use your own clothing data and how to generate data similar to a digital wardrobe? We look forward to your reply and appreciate it

**Comment by bharat-b7** [comment]
To generate your own wardrobe, you'll have to do multi-mesh registration on scans as described in the paper. This code is not released currently.

**Comment by yangbiaobiao500** [comment]
RuntimeError: Error copying tensor to device: /job:localhost/replica:0/task:0/device:GPU:1. /job:localhost/replica:0/task:0/device:GPU:1 unknown device.
I do as you said to un the code on a single GPU comment out the lines containing with tf.device('gpu:x')


![Screenshot from 2019-12-11 13-39-03](https://user-images.githubusercontent.com/48718462/70594486-a66bd180-1c1b-11ea-97aa-b9bbfcc08ec5.png)
Only here tf.device ('gpu: x')
But the results have not changed，we look forward to your answer and appreciate it.

**Comment by Qingcsai** [comment]
@yangbiaobiao500 Well, you should notice the indent problem when u only comments.
If you are using only one GPU, I think it's better to change all the

> with tf.device('/gpu:x') 

with 

> with tf.device('/gpu:0') 

Once you set '/gpu:0', it will automatically call the first GPU you have, which is the only one u have.

**Comment by Vikas-Sony** [comment]
Hi,

Did you figure out how to do multi mesh registration. If yes, can i please get a sample code or maybe steps on how to do that?
