### ISSUE TITLE
What version of tensorflow do you use?  (compatibility with DIRT)

### ISSUE THREAD

**Issue by neonb88** [bharat-b7/MultiGarmentNetwork#13]
This is beautiful work.  Thank you.

# Issue:

I am on a Google Cloud Ubuntu 18.04 Virtual Machine.  I tried running `cd ~/dirt;  pip install tensorflow-gpu==1.13.1;  pip install .` within a `conda` environment because your `README.md` mentions `python2.7` and `tensorflow 1.13`.  But then I get the following DIRT error:

```
  ERROR: Could not find a version that satisfies the requirement 
tensorflow-gpu==1.13 (from dirt===-0.3.0) 
(from versions: 0.12.0rc0, 0.12.0rc1, 0.12.0, 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.2.0rc0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.4.1, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.5.1, 1.6.0rc0, 1.6.0rc1, 1.6.0, 1.7.0rc0, 1.7.0rc1, 1.7.0, 1.7.1, 1.8.0rc0, 1.8.0rc1, 1.8.0, 1.9.0rc0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0rc0, 1.10.0rc1, 1.10.0, 1.10.1, 1.11.0rc0, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.12.0rc0, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.2, 1.12.3, 1.13.0rc0, 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 1.15.0rc0, 1.15.0rc1, 1.15.0rc2, 1.15.0rc3, 1.15.0, 2.0.0a0, 2.0.0b0, 2.0.0b1, 2.0.0rc0, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.1.0rc0, 2.1.0rc1, 2.1.0rc2, 2.1.0)

ERROR: No matching distribution found for tensorflow-gpu==1.13 (from dirt===-0.3.0)
```

Because `pmh47` required `tensorflow 1.6`.

I guess I will try to use his version(s) of `CUDA`, `CUDNN`, `tensorflow`, etc. and then run the rest of your code.  What versions did you use?

**Comment by neonb88** [comment]
I found a simple solution: use `tensorflow 1.13.1` and just do `cd ~;git clone https://github.com/pmh47/dirt.git;cd dirt;pip install .` and then in your `.bashrc` insert the line `export PYTHONPATH=$PYTHONPATH:$HOME/dirt` and voila!  Success!

**Comment by hshreeshail** [comment]
@neonb88 How did you install MPI Mesh (the 2.7 compatible [version](https://github.com/TimoBolkart/mesh)) in the conda environment. The repo only has a Makefile to install in a python virtualenv.

**Comment by hshreeshail** [comment]
> @neonb88 How did you install MPI Mesh (the 2.7 compatible [version](https://github.com/TimoBolkart/mesh)) in the conda environment. The repo only has a Makefile to install in a python virtualenv.

I just used a python virtualenv instead. Works fine that way.
