### ISSUE TITLE
Digital Wardrobe full dataset

### ISSUE THREAD

**Issue by wlhsiao** [bharat-b7/MultiGarmentNetwork#15]
Thanks again for kindly releasing this amazing code base and dataset! 
A question I have about the dataset is: the data I downloaded from the shared [link](https://datasets.d2.mpi-inf.mpg.de/MultiGarmentNetwork/Multi-Garmentdataset.zip) contains 96 scans in total. In the MGN paper Section 4 (Dataset and Experiments), it mentioned that this work used 356 scans for training and testing. 
I'm wondering if all 356 scans are publicly released, or if I'm accessing the wrong link? 
Thanks in advance for any information!

**Comment by bharat-b7** [comment]
The link you are accessing is correct.
We are in the process of anonymising the data before we can release it.
We will release around 100 more garments.

**Comment by wlhsiao** [comment]
Got it, thanks for your kind reply!

**Comment by Frank-Dz** [comment]
> The link you are accessing is correct.
> We are in the process of anonymising the data before we can release it.
> We will release around 100 more garments.

@bharat-b7 Dear Bharat, sorry for bothering you. I want to ask when will the rest of the garments release? Many thanks!

Best,
Frank
