### ISSUE TITLE
how to run the code?

### ISSUE THREAD

**Issue by wolf943134497** [bharat-b7/MultiGarmentNetwork#2]
hi @bharat-b7    thanks for your great work!
can you give me a brief pipeline, which can run the code correctly. 
And  which folder should place the dataset and pretrained model files?

**Comment by bharat-b7** [comment]
Hi,
The file containing sample test data, "test_data.pkl" should be placed in "<code_root>/assets/test_data.pkl", and pretrained files go in "<code_root>/saved_model/".

To run the code: python test_network.py

**Comment by Eby-123** [comment]
@bharat-b7 Hi,
    Running the code:`pytho test_network.py`，it can run without error and the last line of code `print("Done")` works.
    But, the code `mv = MeshViewers((1,2), keepalive=True)` and `mv1 = MeshViewers((1,2), keepalive=True)` does not display the corresponding results.
    How to visualize the result of garment and person? Any advice would be appreciated.
    My enviroment is :
                                 ubuntu16.04, 
                                 python3.5,
                                 tensroflow1.13,
                                 cmake3.10,
                                 gcc5.4,
                                 cuda10.0,
                                 nvidia driver410.48,
                                 dirt0.3.0,
                                 psbody-mesh0.3.

**Comment by bharat-b7** [comment]
Try inserting a breakpoint before the print statement (or just insert ``` raw_input(" Waiting for key press ") ```

**Comment by Eby-123** [comment]
@bharat-b7 
Thank's a lot
