### ISSUE TITLE
How to calculate vertex-to-surface error?

### ISSUE THREAD

**Issue by Qingcsai** [bharat-b7/MultiGarmentNetwork#20]
I wonder how to compute the vertex-to-surface error in the paper mentioned?
I am a little confused by the meaning of the 'surface', could you explain in more detail? 
Besides, how to write the code of computing the vertex-to-surface error?... I want to reproduce the reconstruction precision of the paper (maybe a little bit difficult?...
Here is the equation mentioned about vertex-to-surface error :
![image](https://user-images.githubusercontent.com/41203342/78118587-ca0c8f00-7439-11ea-8beb-c8d1dea3ac94.png)
Thank you for explaining more detailedly!

**Comment by bharat-b7** [comment]
Surface in the above equation refers to the mesh.
To compute vertex-to-surface error: for every vertex on the source mesh find the nearest point (this need not be a vertex) on the target mesh and take the distance between the vertex and this point.
I haven't tested it but ```closest_points()``` in the  MPI mesh package (https://github.com/MPI-IS/mesh/blob/master/mesh/mesh.py) should compute the nearest point on the surface.

**Comment by Qingcsai** [comment]
I Got it! Thanks for your explanation! I will try the method you said!
