### ISSUE TITLE
What's the best way to infer on "no human"?

### ISSUE THREAD

**Issue by andrewjong** [bharat-b7/MultiGarmentNetwork#21]
I'm using MGN to parse a video, frame by frame. In some frames, the person walks out of frame, resulting in no pose. This causes OpenPose to produce an empty array instead of the standard (batch) x 25 x 3.

How should I format the pose to pass to MGN in this case, such that MGN will produce an empty or no mesh? The `PoseShapeOffsetModel` doesn't seem to handle a `None` input. I thought about passing a batch x 25 x 3 array of `0`s, but this would seem to imply that the person is located at the top left pixel. How would MGN handle this case?

Thanks!

**Comment by bharat-b7** [comment]
Hi, you could just not run MGN on the frame if openpose doesn't detect a human. Or am I misunderstanding this?

**Comment by andrewjong** [comment]
Huh, you're right. I've been thinking about this the wrong way. Thanks for answering these simple questions!
