### ISSUE TITLE
Order of vertices from `get_results(...)` output always the same?

### ISSUE THREAD

**Issue by neonb88** [bharat-b7/MultiGarmentNetwork#22]
Hi Bharat and all other readers,

Thanks for all your work, Mr. Bhatnagar.  Are the vertices of SMPL-high-res (produced by `get_results(m, inp, ...)` from `test_network.py`) always in the same order?  For instance I see vertex "1" and "2" are points in the head of the model, on the left side (from the model's perspective).  Will this always be the case if I run that function `get_results(...)`?

I suspect the answer is yes, because two .obj meshes saved at two different times both have the first face as `f 6893 3 6892`, but I would like a guarantee, because I'm about to write some testing code that assumes it's true.

Also, same question for "regular" low-res SMPL: are the vertices always in the same part of the body?

Thanks,
Nathan

**Comment by bharat-b7** [comment]
Vertex ordering remains the same for both low and high res SMPL

**Comment by neonb88** [comment]
Do you know if this is true for every work using SMPL?  (ie. SMPLify-X, HMR)
