### ISSUE TITLE
more dataset

### ISSUE THREAD

**Issue by electronicliujiang** [bharat-b7/MultiGarmentNetwork#23]
Hello, the paper said that there are 712 digital clothing, but the data set you provided seems to be only a part, can you provide the remaining data set? thank you very much!

**Comment by bharat-b7** [comment]
Added more garments at: https://datasets.d2.mpi-inf.mpg.de/MultiGarmentNetwork/Multi-Garmentdataset_02.zip

**Comment by electronicliujiang** [comment]
Thank you for your reply, is there any other body scan data and corresponding texture？

**Comment by bharat-b7** [comment]
I'm not aware of other datasets with garments registered from real human scans. You can still look up for synthetic (simulated) datasets.

**Comment by gongfc** [comment]
Are there any other texture data sets？
