### ISSUE TITLE
How to generate 'image_x' in test_data.pkl?

### ISSUE THREAD

**Issue by Frank-Dz** [bharat-b7/MultiGarmentNetwork#29]
Hi~ 
I ran PGN on my cropped image:
![image](https://user-images.githubusercontent.com/55009565/79640475-61a50800-81c4-11ea-8a10-345b1f0c5f99.png)
and got segmentation result:
023622.mat
023622.png
023622_vis.png

The following is 023622_vis.png:
![image](https://user-images.githubusercontent.com/55009565/79640488-72557e00-81c4-11ea-92ce-411fa16881d4.png)

The following is 023622.mat:
![image](https://user-images.githubusercontent.com/55009565/79640458-50f49200-81c4-11ea-8e7f-337c07d83024.png)

Then how can we build data in the test_data.pkl for image_0 (suppose this is the firt image)?
Since I noticed that the image_x in test_data.pkl is
![image](https://user-images.githubusercontent.com/55009565/79641395-e0507400-81c9-11ea-948d-5962c99851df.png)

The color is quite different from the PGN one.

Thanks again!

Best,
Frank

**Comment by neonb88** [comment]
Hi,

I appreciate your willingness to ask questions whenever you are stuck.  Some people are too proud to do that.  I can send you some code I used to fix some of these issues, but please be patient.  I will not do it right now; maybe tomorrow.  E-mail me at neonb88@yahoo.com and I can send you my cell phone number.  Happy to collaborate

Cheers,
Nathan

**Comment by neonb88** [comment]
You can find all the values of the colors, though, and set them equal to other values.  It's something like:

```
WHITE = [255, 255, 255]
hair_red_color= [255,0,0]
img [ np.where(img==hair_red_color)   ] = WHITE
```

**Comment by hy-i-hairy** [comment]
> 但是，您可以找到所有颜色值，并将它们设置为与其他值相同。就像这样：
> 
> ```
> WHITE = [255, 255, 255]
> hair_red_color= [255,0,0]
> img [ np.where(img==hair_red_color)   ] = WHITE
> ```

Hello, I'm sorry for the sudden interruption. I would like to ask how long sleeves and short sleeves or trousers and shorts are marked in different colors?
Looking forward to your reply.Thank you
