### ISSUE TITLE
Wrong Prediction using MGN.

### ISSUE THREAD

**Issue by Frank-Dz** [bharat-b7/MultiGarmentNetwork#30]
To test the network, I construct my_testdata.pkl.
[my_testdata.pkl.zip](https://github.com/bharat-b7/MultiGarmentNetwork/files/4532147/my_testdata.pkl.zip)

The data contains 8 images. And the person stands like this:
![image](https://user-images.githubusercontent.com/55009565/80267826-a6093a00-86d5-11ea-8d99-ea15d1d60112.png)

Yet the output of test_network is wrong:
![image](https://user-images.githubusercontent.com/55009565/80267862-e963a880-86d5-11ea-9ef1-4ef47d37466a.png)

Since the girl is in a T-shirt yet the network gives me a shirt.

I have set the garment type:
```
detected_garment1 = 'TShirtNoCoat'
detected_garment2 = 'Pants'
 TEMPLATE = pkl.load(open('assets/allTemplate_withBoundaries_symm.pkl', 'rb'), encoding='latin1')
  for n, gar in enumerate(TEMPLATE.keys()):
    if gar ==detected_garment1:
      print('current garment: ', gar)
      test_data["vertexlabel"][0][np.where(TEMPLATE[gar][1])[0]] = (n + 1)  # 0 is kept for skin

  for n, gar in enumerate(TEMPLATE.keys()):
    if gar == detected_garment2:
      print('current garment: ', gar)
      test_data["vertexlabel"][0][np.where(TEMPLATE[gar][1])[0]] = (n + 1)  # 0 is kept for skin
```

Anyone can help?

(To test the .pkl, when you read it in, just set
```
dat = pkl.load(open('assets/my_testdata.pkl', "rb"), encoding="latin1")  # added this encoding stuff for Python3
# dat = {k: v[config.train.batch_size:] for k, v in dat.items()}  # added this to slice the data
```

Thanks in advance!

**Comment by bharat-b7** [comment]
It seems that you are supplying wrong `vertexlablel`. Ensure that `test_data["vertexlabel"][0][<garment vertices>]` contains 0s for all garments not present in the input image.

**Comment by Frank-Dz** [comment]
> It seems that you are supplying wrong `vertexlablel`. Ensure that `test_data["vertexlabel"][0][<garment vertices>]` contains 0s for all garments not present in the input image.

OK! Thanks!

BTW, if it is possible to release the train code?
Thanks again!

Best,
Frank

**Comment by neonb88** [comment]
@Frank-Dz Did you at least get the SMPL model to look like the girl in the image?  I've been having trouble getting the right shape parameters "beta" from a modified version of `test_network.py`

**Comment by Frank-Dz** [comment]
> @Frank-Dz Did you at least get the SMPL model to look like the girl in the image? I've been having trouble getting the right shape parameters "beta" from a modified version of `test_network.py`

Yep the shape seems right.
I sent you an email. pls check.

**Comment by neonb88** [comment]
> BTW, if it is possible to release the train code?
> 
> Best,
> Frank

Look (`grep`) for `def train` in `network/base_network.py`.  On my machine, it's line 431.  Unfortunately I don't know details of how to use this yet.  You can read [BLB's paper](https://virtualhumans.mpi-inf.mpg.de/papers/bhatnagar2019mgn/bhatnagar2019mgn.pdf).  Hope that helps!  :smile:

**Comment by xiezhy6** [comment]
@Frank-Dz 
Hi, How do you get the "J_2d_x" in the testdata.pkl from the openpose estimated results?

**Comment by Frank-Dz** [comment]
You need to understand the meaning of the output of openpose then make them into json.


Best,
Frank




On 08/9/2020 16:42，xiezhy6<notifications@github.com> wrote：

@Frank-Dz
Hi, How do you get the "J_2d_x" in the testdata.pkl from the openpose estimated results?

**Comment by xiezhy6** [comment]
> You need to understand the meaning of the output of openpose then make them into json. Best, Frank On 08/9/2020 16:42，xiezhy6<notifications@github.com> wrote： @Frank-Dz Hi, How do you get the "J_2d_x" in the testdata.pkl from the openpose estimated results? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks for your rely.
I use the code mentioned in this [comment](https://github.com/bharat-b7/MultiGarmentNetwork/issues/12#issuecomment-582240961) to obtain the data for "J_2d_x". I think it work for me.
