### ISSUE TITLE
Question about digital wardrobe/training data.

### ISSUE THREAD

**Issue by Frank-Dz** [bharat-b7/MultiGarmentNetwork#32]
Hi~ @bharat-b7 Thanks for your great job!
Here I am a little confused. The paper claims you process a dataset of 356 scans of people in varied clothing, poses and shapes and use these 356 3D scans of people to train the network. And 70 scans are held out for testing.
But the data: Multi-Garmentdataset.zip only contains 96 garments.
![image](https://user-images.githubusercontent.com/55009565/80561727-f3f4a980-8a17-11ea-8cc9-31ecb2a8e090.png)

Am I missing something?
Thanks in advance!

**Comment by Frank-Dz** [comment]
Similar question: [https://github.com/bharat-b7/MultiGarmentNetwork/issues/23](https://github.com/bharat-b7/MultiGarmentNetwork/issues/23)

**Comment by bharat-b7** [comment]
Added more garments at https://datasets.d2.mpi-inf.mpg.de/MultiGarmentNetwork/Multi-Garmentdataset_02.zip

**Comment by Frank-Dz** [comment]
> Added more garments at https://datasets.d2.mpi-inf.mpg.de/MultiGarmentNetwork/Multi-Garmentdataset_02.zip

Thanks!

**Comment by Frank-Dz** [comment]
> Added more garments at https://datasets.d2.mpi-inf.mpg.de/MultiGarmentNetwork/Multi-Garmentdataset_02.zip

If it is possible to share the texture map like before?
Thanks again for your great work!
