### ISSUE TITLE
ImportError: No module named 'psbody.smpl'

### ISSUE THREAD

**Issue by Eby-123** [bharat-b7/MultiGarmentNetwork#4]
@bharat-b7 Hi,thank's for your great work!

I have install the mesh packages successfully.Because when running the codes:
   ` from psbody.mesh import Mesh, MeshViewers`
there's no problem.

But when running the codes:
    ` from psbody.smpl import load_model`
it returns:
   `ImportError: No module named 'psbody.smpl'`

How should I do?Any advice would be appreciated.

**Comment by bharat-b7** [comment]
Hi, thanks for pointing this out. I have removed the dependencies from ch_smpl.py

**Comment by anuragmundhada** [comment]
Facing this same issue - could you point to which commit of the mesh packages are you using?  The dependency is still present in visualize_garments.py.

Also, the current commit of mesh (d8385edbe2faccdb7099538954d7f2323f04e36b) does not work with Python2.

**Comment by Eby-123** [comment]
@bharat-b7 
Hi,when I run the file:`dress_SMPL.py`
```
Traceback (most recent call last):
  File "dress_SMPL.py", line 15, in <module>
    from utils.smpl_paths import SmplPaths
  File "/home/wuyibin/MultiGarmentNetwork-master_python3/utils/smpl_paths.py", line 6, in <module>
    from psbody.smpl import load_model
ImportError: No module named 'psbody.smpl'
```
To dress 3D person from images,do you need to run the file"dress_SMPL.py"?

**Comment by bharat-b7** [comment]
Updated dependencies in utils/smpl_paths.py

**Comment by bharat-b7** [comment]
> Facing this same issue - could you point to which commit of the mesh packages are you using? The dependency is still present in visualize_garments.py.
> 
> Also, the current commit of mesh (d8385edbe2faccdb7099538954d7f2323f04e36b) does not work with Python2.

Please raise an issue at https://github.com/MPI-IS/mesh for support issue with Python2

**Comment by Eby-123** [comment]
@bharat-b7 
thank's for your help.I've solve this problem.
By changing the code in  utils/smpl_paths.py:
```
from psbody.smpl import load_model
from psbody.smpl.serialization import backwards_compatibility_replacements
```
to:
```
from lib.serialization import load_model
from lib.serialization import backwards_compatibility_replacements
```
