### ISSUE TITLE
Unable to run test_network.py getting dimension error?

### ISSUE THREAD

**Issue by ZhiRuoo** [bharat-b7/MultiGarmentNetwork#5]
Hi @bharat-b7 , thanks for sharing awesome code.
I am getting the following error when running test_network.py while loading the model.

**ValueError: Argument must be a dense tensor: [array([255, 255, 255]), array([65,  0, 65]), array([ 0, 65, 65]), array([145,  65,   0]), array([145,   0,  65]), array([  0, 145,  65])] - got shape [6, 3], but wanted [6]**

Pls help....!
Thanks in advance

**Comment by bharat-b7** [comment]
Hi, I'm unable to reproduce you error. Could you provide more details?
