### ISSUE TITLE
where is test_data.pkl

### ISSUE THREAD

**Issue by ljiqy** [bharat-b7/MultiGarmentNetwork#54]
Hi,
    when run your netowrk, I found there is no test_data.pkl in asset folder, can you provide it to me for reference?

thank you!

**Comment by bharat-b7** [comment]
It should be present here: https://datasets.d2.mpi-inf.mpg.de/MultiGarmentNetwork/weights.zip

**Comment by ljiqy** [comment]
thank you for you reply! I have find it.
