### ISSUE TITLE
How to generate the digital wardrobe?

### ISSUE THREAD

**Issue by Eby-123** [bharat-b7/MultiGarmentNetwork#9]
@bharat-b7 
Hi,the digital wardrobe work very well in training the MGN.
And if I want to generate a digital wardrobe for myself,should I buy some machines?
Any advice about generating the digital wardrobe will be appreciated.

**Comment by bharat-b7** [comment]
To generate your own wardrobe, you'll have to do multi-mesh registration on scans as described in the paper.
